---
- name: Setup Promtail to send Docker logs to Loki
  hosts: singularpromtail
  become: yes
  vars:
    compose_file: "/path/to/docker-compose.yml" # replace this path
    stack_name: "promtail-docker"
  tasks:

    - name: Ensure Docker Compose is installed
      block:
        - name: Get system architecture
          shell: uname -m
          register: arch

        - name: Get system OS
          shell: uname -s
          register: os

        - name: Download Docker Compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ os.stdout }}-{{ arch.stdout }}"
            dest: /usr/local/bin/docker-compose
            mode: '0755'
      become: true

    - name: Create directory for Promtail configuration
      ansible.builtin.file:
        path: /etc/promtail
        state: directory
        mode: '0755'

    - name: Create Promtail configuration file
      ansible.builtin.copy:
        dest: /etc/promtail/promtail-config.yml
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 0

          positions:
            filename: /tmp/positions.yaml

          clients:
            - url: http://modifyme:3100/loki/api/v1/push

          scrape_configs:
            # modify job below to match your needs
            - job_name: system
              static_configs:
              - targets:
                  - localhost
                labels:
                  job: varlogs
                  __path__: /var/log/*log

            - job_name: docker
              docker_sd_configs:
                - host: unix:///var/run/docker.sock
              relabel_configs:
                - source_labels: [__meta_docker_container_name]
                  target_label: container
                - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
                  target_label: service