---
- name: Add public key to authorized_keys and configure sudoers
  hosts: testgroup
  become: yes
  tasks:
    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/home/elrey/.ssh/id_rsa.pub') }}"