---
- name: Remove public key from authorized_keys and revert sudoers changes
  hosts: testgroup
  become: yes
  vars:
    ansible_user: elrey
  tasks:
    - name: Remove public key from authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: absent
        key: "{{ lookup('file', '/home/elrey/.ssh/id_rsa.pub') }}"

    - name: Remove sudoers entry
      lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: '^%{{ ansible_user }}'